alias ga.="ga ."
alias gb="git branch"
alias gbd="git branch -D"
alias gc="git commit"
alias gca="git commit -a"
alias gcam="git commit -a -m"
alias gcm="git commit -m"
alias gco!="git checkout -- ."
alias gcob="git checkout -b"
alias gfo="run 'git fetch origin'"
alias gl="git log --pretty=format:'%h %C(yellow)%an%C(reset) %s%C(green)%d%C(reset)'"
alias gld="git log --pretty=format:'%h %C(cyan)%cd %C(yellow)%an%C(reset) %s%C(green)%d%C(reset)' --date=short"
alias gl?="gl -i --grep"
alias gld?="gld -i --grep"
alias gl5="gl -5"
alias gph="run 'git push heroku master'"
alias gm="git merge"
alias gmm="run 'git merge origin/master'"
alias gr="git remote -v"
alias gsc="run 'git stash clear'"
alias gss="git stash save"
alias gsl="git stash list"
alias gsp="git stash pop"
alias gundo="git reset HEAD^ --soft"
