alias gb="git branch"
alias gbd="git branch -D"
alias gc="git commit"
alias gca="git commit -a"
alias gcm="git commit -m"
alias gcam="git commit -a -m"
alias gco!="git checkout -- ."
alias gcob="git checkout -b"
alias gcom="git checkout master"
alias gl="git log --pretty=format:'%h %C(yellow)%an%C(reset) %s%C(green)%d%C(reset)'"
alias gld="git log --pretty=format:'%h %C(cyan)%cd %C(yellow)%an%C(reset) %s%C(green)%d%C(reset)' --date=short"
alias gph="git push heroku master"
alias gm="git merge"
alias gmm="git merge root/master"
alias gmm!="git checkout master && git merge root/master && git push origin master"
alias gr="git remote -v"
alias gs="git status -sb"
alias gundo="git reset HEAD^ --soft"
alias gshipped="git log --pretty=format:'%h %C(cyan)%cd %C(reset)%s' --date=short --since=1.week | grep \"Merge remote-tracking branch\" | sed \"s/Merge remote-tracking branch //\" | sed \"s/'//g\""
