alias d="docker"

alias dc="docker-compose"
alias dc+="docker-compose up -d"
alias dc-="docker-compose down"
alias dc~="docker-compose restart"
alias dcx="docker-compose exec app"
alias dbash="docker-compose exec app bash"
alias dlog="docker-compose logs -f"
alias dlogs="dlog"

alias ds="docker-sync"
alias ds+="docker-sync start"
alias ds-="docker-sync stop"
alias ds~="docker-sync stop && docker-sync start"
