tap 'homebrew/cask-cask'
tap 'homebrew/services'

brew 'ag'
brew 'jq'
brew 'wget'

brew 'chruby'
brew 'ruby-install'

cask '1password'
cask 'dropbox'
cask 'iterm2'
cask 'keepingyouawake'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
